import React from 'react';
import { OrgPicker } from '../OrgPicker';
import { StatCard } from '../StatCard';
import { useOrgInvoices } from '../../../hooks/queries/useCorporateDashboard';
import type { OrganizationRow } from '../../../lib/organizations-store';

export function InvoicesTab({
  orgs,
  activeOrgId,
  onSelectOrg,
}: {
  orgs: OrganizationRow[];
  activeOrgId: string | null;
  onSelectOrg: (id: string) => void;
}) {
  const { data: invoices = [] } = useOrgInvoices(activeOrgId);

  const outstanding = invoices
    .filter(i => i.status === 'issued' || i.status === 'overdue')
    .reduce((s, i) => s + Number(i.total_amount), 0);
  const paid = invoices
    .filter(i => i.status === 'paid')
    .reduce((s, i) => s + Number(i.total_amount), 0);
  const currency = invoices[0]?.currency ?? '';

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h1 className="text-xl font-bold text-gray-900">Invoice history</h1>
        <OrgPicker orgs={orgs} activeOrgId={activeOrgId} onSelect={onSelectOrg} />
      </div>
      {invoices.length === 0 ? (
        <div className="bg-white rounded-2xl p-6 border border-gray-100 text-sm text-gray-500">
          No invoices yet for this period. Monthly invoices are generated by the platform's billing job on the 1st of every month.
        </div>
      ) : (
        <>
          <div className="grid sm:grid-cols-3 gap-4">
            <StatCard icon="💰" label="Outstanding"     value={`${outstanding.toLocaleString('en-US')} ${currency}`} color="orange" />
            <StatCard icon="✅" label="Paid this year"   value={`${paid.toLocaleString('en-US')} ${currency}`}        color="emerald" />
            <StatCard icon="📄" label="Total invoices"   value={String(invoices.length)}                              color="blue" />
          </div>
          <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 border-b border-gray-100">
                <tr>
                  {['Period','Departments','Amount','Status','Due','Ref'].map(h => (
                    <th key={h} className="text-left py-3 px-4 font-semibold text-gray-600 text-xs uppercase tracking-wide">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {invoices.map(inv => {
                  const deptCount = Object.keys(inv.department_breakdown ?? {}).length;
                  return (
                    <tr key={inv.id} className="hover:bg-gray-50">
                      <td className="py-3.5 px-4">
                        {new Date(inv.period_start).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}
                      </td>
                      <td className="py-3.5 px-4 text-xs text-gray-500">
                        {deptCount === 0 ? '—' : `${deptCount} dept${deptCount === 1 ? '' : 's'}`}
                      </td>
                      <td className="py-3.5 px-4 font-medium">
                        {Number(inv.total_amount).toLocaleString('en-US')} {inv.currency}
                      </td>
                      <td className="py-3.5 px-4">
                        <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${
                          inv.status === 'paid'     ? 'bg-emerald-100 text-emerald-700' :
                          inv.status === 'issued'   ? 'bg-blue-100 text-blue-700' :
                          inv.status === 'overdue'  ? 'bg-rose-100 text-rose-700' :
                          inv.status === 'disputed' ? 'bg-amber-100 text-amber-700' :
                                                      'bg-gray-100 text-gray-600'
                        }`}>{inv.status}</span>
                      </td>
                      <td className="py-3.5 px-4 text-xs text-gray-500">
                        {inv.due_at ? new Date(inv.due_at).toLocaleDateString() : '—'}
                      </td>
                      <td className="py-3.5 px-4 font-mono text-xs text-gray-500">
                        {inv.external_ref ?? inv.id.slice(0, 8) + '…'}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}
