import React, { useState } from 'react';
import { ChevronDown } from 'lucide-react';

/**
 * Frequently asked questions on the homepage. Doubles as conversion
 * surface (answers the objections customers raise before booking) and
 * SEO surface (FAQPage JSON-LD generated by HomePage's <script>
 * embedding so Google can show the rich-result accordion in search).
 */

interface QA {
  question: string;
  answer:   string;
}

export const HOME_FAQS: QA[] = [
  {
    question: 'How does FlyttGo work as a marketplace?',
    answer:
      'FlyttGo is a coordination platform — we don’t own vans or employ drivers. You enter your move, we match you with licensed local providers in your country, you compare prices and reviews, you book with escrow protection. The provider performs the move; we hold the money until you confirm completion.',
  },
  {
    question: 'Can I really pay in cash on delivery?',
    answer:
      'Yes — in five of our six markets (US, Canada, Germany, France, United Kingdom). You pay a 30% deposit online up front to confirm the booking; the remaining 70% is paid in cash to your driver on delivery. Norway is card-only for now (Vipps support is on the roadmap).',
  },
  {
    question: 'What happens if my mover damages something?',
    answer:
      'Every booking is covered by goods-in-transit insurance up to $50,000 (or local equivalent). Claims go through your provider’s insurer. The FlyttGo support team helps you file the claim and adjudicates a refund of the platform deposit if the provider is at fault.',
  },
  {
    question: 'How quickly can I get a quote?',
    answer:
      'Under 60 seconds. Pick your country, type your pickup and drop-off addresses, choose your date — your quote appears immediately and is held for 30 minutes while you decide.',
  },
  {
    question: 'Do prices change at peak times?',
    answer:
      'Yes — at peak rush hours (07:00–09:00 and 17:00–19:00) we apply a 1.3× surge multiplier so we can guarantee a vetted driver. The surge is shown clearly on your quote before you confirm; you can pick a different time-of-day to avoid it.',
  },
  {
    question: 'Can I cancel after I’ve booked?',
    answer:
      'Yes. Card-paid bookings are fully refundable up to 24 hours before the move. Cash-method bookings refund the deposit on the same window. Inside 24 hours we charge the deposit (the driver may have already turned down other work to keep your slot).',
  },
];

export default function HomeFAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  return (
    <section className="bg-[#fafaf7] py-16 sm:py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-10">
          <p className="text-amber-600 text-xs font-bold uppercase tracking-wider mb-2">
            Frequently asked questions
          </p>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Everything you need to know before you book.
          </h2>
        </div>

        <div className="space-y-3">
          {HOME_FAQS.map((qa, i) => {
            const isOpen = openIdx === i;
            return (
              <details
                key={qa.question}
                open={isOpen}
                onClick={(e) => { e.preventDefault(); setOpenIdx(isOpen ? null : i); }}
                className="bg-white border border-slate-200 rounded-xl overflow-hidden hover:border-amber-300 transition-colors"
              >
                <summary className="cursor-pointer list-none flex items-center justify-between gap-4 px-5 py-4">
                  <span className="font-semibold text-slate-900 text-base">{qa.question}</span>
                  <ChevronDown
                    size={18}
                    className={`text-slate-400 flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`}
                  />
                </summary>
                <div className="px-5 pb-4 text-sm text-slate-600 leading-relaxed">
                  {qa.answer}
                </div>
              </details>
            );
          })}
        </div>

        {/* JSON-LD FAQPage so Google can show the rich-result accordion */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type':    'FAQPage',
              mainEntity: HOME_FAQS.map(qa => ({
                '@type':         'Question',
                name:            qa.question,
                acceptedAnswer:  { '@type': 'Answer', text: qa.answer },
              })),
            }),
          }}
        />
      </div>
    </section>
  );
}
